name = Sys-Hostname

[ReadmeFromPod]
; disable = true
filename = doc/Sys-Hostname.rakudoc

[PruneFiles]
; match = ^ 'xt/'o

[Badges]
provider = github-actions/linux.yml
provider = github-actions/macos.yml
provider = github-actions/windows.yml

[UploadToZef]
